version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - main-app
      - malicious-container
    networks:
      - app-network

  main-app:
    build:
      context: ./main-app
    expose:
      - "80"
    networks:
      - app-network

  malicious-container:
    build:
      context: ./malicious-container
    expose:
      - "80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge